version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres-notifications
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: notifications
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-notifications
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"  
    depends_on:
      - postgres

volumes:
  postgres_data:
  # Copia el archivo SQL al contenedor de PostgreSQL:
  # docker cp notifications_postgres.sql postgres-notifications:/notifications_postgres.sql
  # Ingresa al contenedor:
  #docker exec -it postgres-notifications bash
  #Ejecuta el SQL dentro del contenedor:
  #psql -U root -d notifications -f /notifications_postgres.sql
